version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes: 
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
    ports:
      - 5050:80
      
  # postgres:
  #     image: "postgres:9.6.1"
  #     ports:
  #       - "5432:5432"
  #     environment:
  #       POSTGRES_USER: "test"
  #       POSTGRES_PASSWORD: "test"
  #       POSTGRES_DB: "test"

